### ISSUE TITLE
Feat Request: Delete sample

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [jeremysmithco/railsinspire#98]
For some reason, I created one sample but posted two. When I tried to delete one, I noticed that there isn't a delete button for the sample.

**Comment by jeremysmithco** [comment]
Hey Pedro, thanks for pointing this out! I'm not sure why I didn't add deletion when I first built this, but clearly I didn't, ha! 😅

I'll delete the duplicate when I roll this change out. Thanks for posting on RailsInspire! 🙏

**Comment by PedroAugustoRamalhoDuarte** [comment]
Thanks @jeremysmithco !!
